name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Azure WebApp
    #  uses: Azure/webapps-deploy@v2
    #  with:
        # Name of the Azure Web App
    #    app-name: githookvnext2393
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
    #    publish-profile: 
        # Enter an existing Slot other than the Production slot
    #    slot-name: production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
    #    package: .
        # Enter the start up command. For ex. dotnet run or dotnet run
    #    startup-command: dotnet GitHook.WebHook.dll
