name: FunctionDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --no-restore src
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o branchprotectFunc  src/BranchProtect
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: $ {{  secrets.FUNCTIONAPPNAME}} # Replace with your app name
        publish-profile: ${{ secrets.FUNCTIONPUBLISHPROFILE }} # Define secret variable in repository settings as per action documentation
        package: './branchprotectFunc' 
