name: WebHookDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o webhookApi  src/GitHook.WebHook
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ secrets.WEBHOOKAPPNAME}} # Replace with your app name
        publish-profile: ${{ secrets.WEBHOOKPUBLISHPROFILE }} # Define secret variable in repository settings as per action documentation
        package: './webhookApi' 
